[feat] - Single Sided Asset Staking
Zilliqa/community-contracts pull request #1
Opened 2021-11-09 22:18 UTC by Elliott-Green

- [X] As an admin, I can create a pool where users can stake (deposit) a specific token.
```fungible_token_contract => lktoken_contract => ssas_contract```
- [X] As an admin, I can set a reward token for each pool. The rewards will have a duration (e.g. 60 days), reward token address (e.g. stake token A get token B, or stake token A get token A) and amount (deposited by the admin). The rate will be variable and calculated depending on:
  - [X] the number of tokens deposited by the users 
```let list_sum```
  - [X] the number of rewards distributed
```SUM(amount of entries with an ADT.UserSSAS balance in past_snapshot_pool at an epoch) / immutable_reward_per_epoch```
```Could be improved```
  - [X] the number of rewards to be paid
```user_share_of_rewards = muldiv currently_deposited_lktokens immutable_reward_per_epoch total_sum_at_epoch;```
- [X] As an admin, I can recover tokens from the contract
```transition AdminReclaimRewards() (for rewards, not user tokens)```
- [X] As an admin, I can set a lock period for each pool. By default, we want 7 days.
  ```epoch_period_length: Uint128, (* ~2500bpd * 7d = 17500b as uint *) (currently immutable)```
- [X] As a user, I can stake tokens on an existing pool and get rewards. 
```transition Deposit(deposit_amount: Uint128)```
- [X] As a user, I can claim rewards at any time.
```transition ClaimRewards(claim_snapshot: Uint128)```
- [X] As a user, I can withdraw my tokens at any time:
```transition Withdraw()```
``` Could be improved```
  - [X] If within lock period, a 10% fee is charged. Those tokens are burnt (or left for the admin to collect)
```_eventname : "TaxableWithdrawSuccess";```
  - [X] If out of lock period, no fee is charged.
```e = {_eventname : "NonTaxableWithdrawSuccess"; ```

# Community Contracts

## Single Sided Asset Staking

Single Sided Asset Staking is locking up a fungible token and being returned an equal amount of "" tokens, representing the deposted or "staked" amount.

### Fungible Tokens

A ZRC-2 fungible token.

We will be calling Transfer/TransferTo and the respective allowance mechanism to move the fungible tokens into  tokens.

### SingleSidedAssetStaking.scilla

A contract that takes an inital deposit of a tokens, then over time, depositing users that meet some time eligiblity are rewarded a percentage of a total amount of rewards of either the same token contract, or an entirely new token.

The contract allows users to call deposit and be entered into a map called ```pool```, a block is set in the future which an epoch occurs. Whenever a transaction is processed by the contract and the current block is in the future of the epoch, a reward calcluation ```get_updated_reward_map_if_eligible``` is performed which iterates ```pool``` entries and determines if the user is eligible for rewards, and if so, what the percentage that the user owns of the overall pool at the time of the epoch. This 500 map entries the worst case gas cost is approxomately 25 ZIL.

```ocaml
type UserSSAS  =  | UserSSAS of BNum    (* block entered staking *)
                                Uint128 (* deposited tokens *)
```

When users data is stored onchain, we store the block they entered (or re-entered) the staking contract, and when they claim for a particular epoch, we calculate the tax free lock as the deposit block time (as shown above) plus ```minimum_lock_time_no_tax```

When users have deposited for longer than ```epoch_period_length``` blocks, on the next epoch they will be eligible for rewards when the calculation runs.

## Testing

### Contract Setup

* DEPLOY FungibleToken.scilla as Stake_FT
* DEPLOY FungibleToken.scilla as Reward_FT
* DEPLOY SingleSidedAssetStaking.scilla as SSAS(Stake_FT, Reward_FT, TAX, EPOCH, REWARD_AMOUNT_PER_EPOCH)
Once the contract is deployed, any transition call will trigger an epoch when ```NOW >= time_to_take_snapshot```

### Owner Setup

* CALL Reward_FT.IncreaseAllowance(SSAS,200000000000000)
* CALL SSAS.OwnerTopUpRewards(200000000000000)
The contract now has funds, owner can also reclaim unclaimed funds using ```OwnerReclaimRewards```

### User Depositing -  InitalDepositSuccess

* CALL Stake_FT.IncreaseAllowance(SSAS,500)
* CALL SSAS.Deposit(1)
Now we have an entry in ```pool``` with a block in the future where we become eligible for rewards
Our Deposit is 1 and we can deposit 499 without recalling IncreaseAllowance.

### User Depositing - IncreasingDepositSuccess - No Reward

* ...time...
* CALL SSAS.Deposit(1)
* TRIGGERS RewardIfEpoch

We are increasing our claim by X - we ensure we continue to track additional increasing deposits.
Assuming we was eligible, since we have deposited, we have a new calculated block for becoming eligible, so instantly become ineligible for readding some stake amount.
Our Deposit is 2 and we can deposit 498 without recalling IncreaseAllowance.

### RewardIfEpoch => reward_map - First Insert

* ...time...
* USER B CALL Stake_FT.IncreaseAllowance(SSAS,100)
* USER B CALL SSAS.Deposit(100)
* TRIGGERS RewardIfEpoch 
Assuming User A was eligible, since user B called and triggered the epoch calculation ```get_updated_reward_map_if_eligible``` determines one entry, User A, is eligible after for-eaching all of the pool rows (currently 1). The calculation determines users percentage at an epoch which requires the total sum at user share hence for this expensive gas calculation as either the whole map is needing to be stored OR dynamically calculated at epoch and accumulativly added to the ```reward``` map

User B's data is inserted into the map after  RewardIfEpoch is finished.
User B's deposit is 100 and needs to call increase allowance to deposit further.

### RewardIfEpoch => reward_map - Additional Inserts

As above, but summed reward value.

* ...time...
* USER B CALL Stake_FT.IncreaseAllowance(SSAS,100)
* USER B CALL SSAS.Deposit(100)
* TRIGGERS RewardIfEpoch

In this test case we can keep track of an increasing deposit.

User B's data is inserted into the map after  RewardIfEpoch is finished.
User B's deposit is 200 and needs to call increase allowance to deposit further.

### RewardIfEpoch - SnapshotSuccess - Inital Insert

First snapshot is saved saved correctly for percentage amount.

* USER A IS VALID FOR REWARDS
* USER B IS NOT VALID FOR REWARDS
* Some transaction TRIGGERS RewardIfEpoch
* User A's percentage of the pool (that are eligible) is rewarded and accumulated in ```reward```
* User B's row is ignored

### RewardIfEpoch - SnapshotSuccess - Addtional Inserts

Additional snapshots are saved correctly for percentage amount.

* USER A IS VALID FOR REWARDS
* USER B IS VALID FOR REWARDS
* Some transaction TRIGGERS RewardIfEpoch
* User A's percentage of the pool (that are eligible) is rewarded and accumulated in ```reward```
* User A's percentage of the pool (that are eligible) is rewarded and accumulated in ```reward```

### ClaimRewards - ClaimRewardsSuccess

User can claim some rewards if present

* Assuming the contract owner has deposted reward tokens.
* USER A HAS AN ENTRY IN ```reward```
* USER A CALL SSAS.ClaimRewards()
* USER A IS RETURNED reward.pair.uint128_amount in reward fungible tokens
* USER A IS REMOVED FROM ```reward```
  

### User Withdrawing Inital - TaxableWithdrawSuccess

Users are impacted with a 10% tax if they withdraw inside the epoch window from their latest deposit or redeposit.

* ASSUMING TAX IS 1000 BPS (10%)
* USER A CALL SSAS.Deposit(10)
* USER A CALL SSAS.Withdraw(10) immediately after deposit.
* USER A RETURNED 9 AND CONTRACT HOLDS 1

Divide bug instead of percent?

* USER A CALL SSAS.Deposit(1)
* USER A CALL SSAS.Withdraw(1)
* NO TAX IS APPLIED
  
### User Withdrawing Inital - NonTaxableWithdrawSuccess

users can withdraw funds with 0% tax if they are outside of the epoch duration from their latest deposit. Redeposits will cause a new epoch tax duration for the entire stake.

* USER A CALL SSAS.Deposit(10)
* ...time...
* USER A CALL SSAS.Withdraw(10)
* USER A RETURNED 10

### Owner Claim Init [...]

2021-11-18 10:34 UTC, bb111189 commented on README.md
> +BUG : reward claim amount is wrong
This should not be there anymore

2021-11-18 13:11 UTC, AmritKumar commented on README.md
> +BUG : reward claim amount is wrong
@Elliott-Green

2021-11-18 13:29 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  token_contract: ByStr20 with end, (* potentially could be immutable *)
```suggestion
  token_contract: ByStr20 with contract end, (* potentially could be mutable *)
```

2021-11-18 13:29 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  reward_token_contract: ByStr20 with end,
```suggestion
  reward_token_contract: ByStr20 with contract end,
```

2021-11-18 13:39 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +    let x = BNum 1 in
`x` is unused. Also the constraints can be better written in the following way:

```
with
    let is_ok_min = uint128_gt early_leave_tax tax_bps_min in
    let is_ok_max = uint128_lt early_leave_tax tax_bps_max in 
                                andb is_ok_min is_ok_max in
    
    =>
```

2021-11-18 13:50 UTC, AmritKumar requested changes

2021-11-18 13:50 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +field pool: Map ByStr20 UserSSAS = Emp ByStr20 UserSSAS
Wondering whether we should change UserSSAS to exclude the user address. Otherwise, it seems a bit redundant to map an address to a struct that also has the address.

2021-11-18 13:50 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +field next_epoch_block: BNum = _creation_block  (* TO DO - now + epoch*)
What is this to do?

2021-11-18 13:50 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +transition RequestDelegatorSwap()
This looks the same as the next few transitions.

2021-11-18 13:50 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +field staged_contract_admin: Option ByStr20 = None {ByStr20}
This field is never written to.

2021-11-18 13:50 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +field current_owner: ByStr20  = contract_owner
This field is never read from or written to.

2021-11-18 16:21 UTC, bb111189 commented
@Elliott-Green  Please implement 2 step contract ownership transfer

2021-11-18 16:24 UTC, bb111189 commented
What is the difference between contract admin and owner? Can they be combined?

2021-11-18 16:59 UTC, Elliott-Green commented on SingleSidedAssetStaking.scilla
> +field next_epoch_block: BNum = _creation_block  (* TO DO - now + epoch*)
I'm trying to calculate the first epoch but can't find a syntax that will let me set this at deploy-time. 
`let calculated_start_epoch = builtin badd _creation_block epoch_period_length in`

2021-11-18 17:02 UTC, Elliott-Green commented
@bb111189 I've pushed ownership features. Re admin, yes it's squashed into owner/staged_owner now.

2021-11-18 18:39 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  let calculated_start_epoch = builtin badd _creation_block epoch_period_length in (* ideally next_epoch_block:= calculated_start_epoch *)
`calculated_start_epoch` is unused.

2021-11-18 18:40 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  match is_valid with
This pattern match really needs to go. It is unnecessary. Just change the previous line to   `andb is_valid_min is_valid_max`

2021-11-19 07:45 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +      | SentRewardsNotAMutipleOfRewardPerEpoch        => Int32 -3
Not used.

2021-11-19 09:20 UTC, AmritKumar requested changes

2021-11-19 09:20 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +transition RevokeOwnershipTransfer()
I am not sure if this is needed.

2021-11-19 11:43 UTC, bb111189 requested changes
There is too much abbreviation. This makes code harder to review. 

For example, `  cel <- current_epoch_length` can be `epoch_length <- current_epoch_length`

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +  maybe_sca <- staged_contract_admin;
Should not be `staged_contract_admin`. It is always None. It  should be `current_owner`

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +field staged_contract_admin: Option ByStr20 = None {ByStr20}
Be more consistent. Use the term admin or owner but not both

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +  early_leave_tax: Uint128,     (* 10 = 1000 *)
```suggestion
  early_leave_tax: Uint128,     (* 10% = 1000 *)
```

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +  paused:=pause_state;
```suggestion
  paused := pause_state;
```

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +      total_rewards_left:= uint128_zero;
```suggestion
      total_rewards_left := uint128_zero;
```

2021-11-19 11:43 UTC, bb111189 commented on README.md
> +We will be calling Transfer/TransferTo and the respective allowance mechanism to move the fungible tokens into  tokens.
```suggestion
We will be calling Transfer/TransferFrom and the respective allowance mechanism to move the fungible tokens into  tokens.
```

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +  total_rewards_left:= new_rewards_left;
```suggestion
  total_rewards_left := new_rewards_left;
```

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +        err = NotContractOwnerOrStagedOwner;
It should not be staged owner. Just contract owner. Create a new error

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +        err = NotContractOwnerOrStagedOwner;
Should be just staging  owner

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +      ThrowError err
Throw a more specific error

2021-11-19 11:43 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +  is_future = builtin blt neb now;  (* is the current block less than the snapshot (the past, will be true on the value of nsbr+1 and future blocks) *)
can rename into is_time_to_reward or something that is more clearer

2021-11-19 13:33 UTC, Elliott-Green commented
I'm working on a few more enhancements, I've left open the comments which I'm working on open.

2021-11-22 07:58 UTC, bb111189 commented
@Elliott-Green  let practice this convention.

For immutable that are later assigned to mutable, prefix it with `init_`

2021-11-22 08:00 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +  inital_contract_owner: ByStr20,
```suggestion
  init_contract_owner: ByStr20,
```

typo. missing i. Imo, can just use `init_`

2021-11-22 09:24 UTC, bb111189 requested changes

2021-11-22 09:24 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +  | Some staged_contract_owner =>
variable name shadowing. Use a different name

2021-11-22 09:24 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +  current_early_leave_tax := new_tax_rate_in_bps;
check to ensure tax is more than 0% and at most 100%

2021-11-22 09:35 UTC, bb111189 requested changes

2021-11-22 09:35 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +              | True => (* tax 10% of users deposit *)
Comment is not accurate. It may not be 10% as it determine by contract owner

2021-11-22 09:35 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +                tax_amount_as_uint256 = builtin div withdraw_amount x;
why is `tax_amount_as_uint256` uint256? It looks uint128 to mee

2021-11-22 09:35 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +                maybe_tax_amount = builtin to_uint128 tax_amount_as_uint256;
I don't think this casting is needed

2021-11-22 09:35 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +                 | None => (* Some math overflow error*)
If there is overflow or underflow, this branch won't be trigger as contract execution will be halted immediately

2021-11-22 09:38 UTC, bb111189 reviewed
For comment like 
```
(*
  Allows owner to reclaim total_taxed_amount (tax = tokens)
*)
```
Make them into single line

2021-11-22 09:38 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +(*
empty comments

2021-11-22 09:42 UTC, bb111189 requested changes

2021-11-22 09:42 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +                    new_amount_locked = builtin sub amount_locked currently_deposited_tokens_after_tax;
I don't think it should be `currently_deposited_tokens_after_tax`. It should be before tax

2021-11-22 09:42 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +      e = {_eventname : "NotSnapshotTime";
This is not neccessary. Else it can be quite spammy

2021-11-22 10:27 UTC, bb111189 requested changes

2021-11-22 10:27 UTC, bb111189 commented on SingleSidedAssetStaking.scilla
> +    modulus_rewards = builtin rem immutable_reward_per_epoch amount;
Remove unused code

2021-11-23 10:49 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  new_empty_staging = Some {ByStr20} new_owner;
```suggestion
  new_staging = Some {ByStr20} new_owner;
```

2021-11-23 10:49 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  staged_contract_owner := new_empty_staging;
```suggestion
  staged_contract_owner := new_staging;
```

2021-11-23 10:50 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  e = {_eventname : "RequestOwnershipTransferSuccess"; staged_contract_owner: new_empty_staging};
```suggestion
  e = {_eventname : "RequestOwnershipTransferSuccess"; staged_contract_owner: new_staging};
```

2021-11-23 10:56 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +(* @dev: Allows current_contract_owner to toggle pause all interactions expect withdraws of inital (pauses withdraw of rewards) *)
```suggestion
(* @dev: Allows current_contract_owner to toggle pause all interactions expect withdrawals of the initial claim (pauses withdraw of rewards) *)
```

2021-11-23 11:07 UTC, AmritKumar requested changes

2021-11-23 11:07 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  new_empty_staging = Some {ByStr20} new_owner;
```suggestion
  new_staging = Some {ByStr20} new_owner;
```

2021-11-23 11:07 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  staged_contract_owner := new_empty_staging;
```suggestion
  staged_contract_owner := new_staging;
```

2021-11-23 11:07 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +  e = {_eventname : "RequestOwnershipTransferSuccess"; staged_contract_owner: new_empty_staging};
```suggestion
  e = {_eventname : "RequestOwnershipTransferSuccess"; staged_contract_owner: new_staging};
```

2021-11-23 11:07 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +(* @dev: Allows current_contract_owner to toggle pause all interactions expect withdraws of inital (pauses withdraw of rewards) *)
```suggestion
(* @dev: Allows current_contract_owner to toggle pause all interactions expect withdrawals of the initial claim (pauses withdraw of rewards) *)
```

2021-11-23 11:21 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +(* @dev: Allows owner can change the rate in which users are impacted by tax, can be zero, can't be more than 10000 *)
```suggestion
(* @dev: Allows owner to change the rate in which users are impacted by tax, can be zero, can't be more than 10000 *)
```

2021-11-23 11:29 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +(* @Requirements: *)
Clean up the comments.

2021-11-23 11:32 UTC, AmritKumar commented on SingleSidedAssetStaking.scilla
> +(* @dev: Implications of a long epoch time are that when a similar  *)
Incomplete comment

2021-12-09 14:08 UTC, closed without merging